rails/3.0/hoge/config/routes.rb
Hoge::Application.routes.draw do
  resources :fugas

end

rails/3.0/hoge/app/models/fuga.rb
class Fuga < ActiveRecord::Base
end

rails/3.0/hoge/app/controllers/fugas_controller.rb
class FugasController < ApplicationController
  # GET /fugas
  # GET /fugas.xml
  def index
    @fugas = Fuga.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @fugas }
    end
  end

  # GET /fugas/1
  # GET /fugas/1.xml
  def show
    @fuga = Fuga.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @fuga }
    end
  end

  # GET /fugas/new
  # GET /fugas/new.xml
  def new
    @fuga = Fuga.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @fuga }
    end
  end

  # GET /fugas/1/edit
  def edit
    @fuga = Fuga.find(params[:id])
  end

  # POST /fugas
  # POST /fugas.xml
  def create
    @fuga = Fuga.new(params[:fuga])

    respond_to do |format|
      if @fuga.save
        format.html { redirect_to(@fuga, :notice => 'Fuga was successfully created.') }
        format.xml  { render :xml => @fuga, :status => :created, :location => @fuga }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @fuga.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /fugas/1
  # PUT /fugas/1.xml
  def update
    @fuga = Fuga.find(params[:id])

    respond_to do |format|
      if @fuga.update_attributes(params[:fuga])
        format.html { redirect_to(@fuga, :notice => 'Fuga was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @fuga.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /fugas/1
  # DELETE /fugas/1.xml
  def destroy
    @fuga = Fuga.find(params[:id])
    @fuga.destroy

    respond_to do |format|
      format.html { redirect_to(fugas_url) }
      format.xml  { head :ok }
    end
  end
end

rails/3.0/hoge/app/helpers/fugas_helper.rb
module FugasHelper
end

rails/3.0/hoge/app/views/fugas/_form.html.erb
<%= form_for(@fuga) do |f| %>
  <% if @fuga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fuga.errors.count, "error") %> prohibited this fuga from being saved:</h2>

      <ul>
      <% @fuga.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fuga_name %><br />
    <%= f.text_field :fuga_name %>
  </div>
  <div class="field">
    <%= f.label :fuga_id %><br />
    <%= f.text_field :fuga_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/3.0/hoge/app/views/fugas/edit.html.erb
<h1>Editing fuga</h1>

<%= render 'form' %>

<%= link_to 'Show', @fuga %> |
<%= link_to 'Back', fugas_path %>

rails/3.0/hoge/app/views/fugas/index.html.erb
<h1>Listing fugas</h1>

<table>
  <tr>
    <th>Fuga name</th>
    <th>Fuga</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fugas.each do |fuga| %>
  <tr>
    <td><%= fuga.fuga_name %></td>
    <td><%= fuga.fuga_id %></td>
    <td><%= link_to 'Show', fuga %></td>
    <td><%= link_to 'Edit', edit_fuga_path(fuga) %></td>
    <td><%= link_to 'Destroy', fuga, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fuga', new_fuga_path %>

rails/3.0/hoge/app/views/fugas/new.html.erb
<h1>New fuga</h1>

<%= render 'form' %>

<%= link_to 'Back', fugas_path %>

rails/3.0/hoge/app/views/fugas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fuga name:</b>
  <%= @fuga.fuga_name %>
</p>

<p>
  <b>Fuga:</b>
  <%= @fuga.fuga_id %>
</p>


<%= link_to 'Edit', edit_fuga_path(@fuga) %> |
<%= link_to 'Back', fugas_path %>

rails/3.0/hoge/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hoge</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>